project:
  type: default
  render:
    - wildfire_database_query_summaries.qmd

params:
  db: wildfire_dev
  localhost: localhost
  user: null

profiles:
  docs:
    project:
      render:
        - wildfire_database_query_summaries.qmd
  chem_build:
    project:
      render:
        - water_chem_functions.qmd
  chem_export:
    project:
      render:
        - wildfire_database_query_nitrate.qmd
        - wildfire_database_query_ammonium.qmd
        - wildfire_database_query_spcond.qmd
        - wildfire_database_query_orthop.qmd

# default set (top-level project.render)
# quarto render -P user:user
# quarto render --profile docs -P user:user
# quarto render --profile chem -P user:user
